### ISSUE TITLE
Corazua v3 working with Caddyserver?

### ISSUE THREAD

**Issue by svenakela** [corazawaf/coraza-caddy#140]
As Coraza v3 has been out for a while, but the Caddyserver docs are still pointing to v2, is it safe to migrate a production WAF to version 3?

**Comment by jcchavezs** [comment]
I think here we are mixing coraza version and coraza-caddy version. This
repo uses coraza 3.1 as per
https://github.com/corazawaf/coraza-caddy/blob/main/go.mod#L8

José Carlos Chávez


man. 11. mars 2024 kl. 11:53 skrev svenakela ***@***.***>:

**Comment by svenakela** [comment]
But of course, you are right! Thanks for the pointer.
