### ISSUE TITLE
add module to caddyserver.com

### ISSUE THREAD

**Issue by rgevaert** [corazawaf/coraza-caddy#15]
Hi,

It would be nice if we could install the module from https://caddyserver.com/download. This way user don't need to compile caddy themselves with the module enabled.

This could help adoption.

thank you for considering this

Rudy

**Comment by jptosso** [comment]
Done! thank you for the reminder.

![image](https://user-images.githubusercontent.com/1236942/181065202-18da7f55-2d60-475a-a735-fda78b82628e.png)

**Comment by rgevaert** [comment]
wow thank you!
