### ISSUE TITLE
The memory leak is still there (#22 not resolved)

### ISSUE THREAD

**Issue by Saperlu** [corazawaf/coraza-caddy#26]
Issue #22 is not resolved, I commented it a few days ago, but I don't know if my message was red because issue is closed and I can't reopen it.

**Comment by anuraaga** [comment]
Hi @Saperlu sorry for the huge delay on getting back on this, have been on/off this week.

Is there a way you could provide a reproduction, perhaps the exact commands for building caddy and running requests?

I have checked the POST test we have here

https://github.com/corazawaf/coraza-caddy/blob/master/coraza_test.go#L109

and could confirm a `/tmp/body*` file being created and then removed automatically.

**Comment by anuraaga** [comment]
Also it would be good if you can try `--with github.com/corazawaf/coraza-caddy@7063a542235df47761e45495a5aa70d5fc7daa4e` in case the lack of a version number caused it to use a cached version.

**Comment by Saperlu** [comment]
OMG, just tried with the commit id and the trick worked. Thank you very much !
