### ISSUE TITLE
log error how to troubleshoot

### ISSUE THREAD

**Issue by rgevaert** [corazawaf/coraza-caddy#33]
Hi,

I am successfully using te coraza waf. However I see this log lines, and I have no idea where to start as it not clear what is producing the warning. Any pointers would be helpful to reduce log messages. thanks!

```
Nov 18 16:49:48 caddy1 caddy[36093]: {"level":"error","ts":1668790188.225632,"logger":"http.handlers.waf","msg":"[client \"x.y.z.a\"] Coraza: Warning.  [file \"\"] [line \"0\"] [id \"1\"] [rev \"\"] [msg \"\"] [data \"\"] [severity \"emergency\"] [ver \"\"] [maturity \"0\"] [accuracy \"0\"] [hostname \"\"] [uri \"/api/ds/query\"] [unique_id \"wkx6KPvYdSLDJ64qAEv\"]\n"}
```

**Comment by EmilePerron** [comment]
Hi there!

I don't work for Coraza, but I did write some documentation for my colleagues that I believe could help you figure out what's going wrong, and how you can fix it: https://gist.github.com/EmilePerron/108298303da71281fdd6aba165cbf424
