### ISSUE TITLE
failed to compile rule

### ISSUE THREAD

**Issue by fanspace** [corazawaf/coraza-caddy#34]
sudo caddy validate
2022/12/09 01:13:17.893	INFO	using adjacent Caddyfile
2022/12/09 01:13:17.894	WARN	Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies	{"adapter": "caddyfile", "file": "Caddyfile", "line": 11}
2022/12/09 01:13:17.895	WARN	http	server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server	{"server_name": "srv6", "http_port": 80}
2022/12/09 01:13:17.895	INFO	tls.cache.maintenance	started background certificate maintenance	{"cache": "0xc0002fd500"}
2022/12/09 01:13:17.913	INFO	tls.cache.maintenance	stopped background certificate maintenance	{"cache": "0xc0002fd500"}
Error: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'waf': provision http.handlers.waf: failed to compile rule (unknown variable): &MULTIPART_PART_HEADERS:_charset_ "!@eq 0" "id:922100,phase:2,block,t:none,msg:'Multipart content type global _charset_ definition is not allowed by policy',logdata:'Matched Data: %{ARGS._charset_}',tag:'application-multi',tag:'language-multi',tag:'platform-multi',tag:'attack-multipart-header',tag:'OWASP_CRS',tag:'capec/1000/255/153',tag:'paranoia-level/1',ver:'OWASP_CRS/4.0.0-rc1',severity:'CRITICAL',chain"

--------------------------------------------------------------------------------

sudo caddy version
v2.6.2 h1:wKoFIxpmOJLGl3QXoo6PNbYvGW4xLEgo32GPBEjWL8o=

------------------------------------------------------------------------

Caddyfile
{
    order coraza_waf first
}
:80 {
	# Set this path to your site's directory.
	root * /usr/share/nginx/www

	# Enable the static file server.
	file_server

	# Another common task is to set up a reverse proxy:
	# reverse_proxy localhost:8080

	# Or serve a PHP site through php-fpm:
	# php_fastcgi localhost:9000
}

:60000 {
 coraza_waf {
        directives `
		SecAction "id:1,pass,log"
	`
        include /home/ubuntu18/coreruleset/coraza.conf-recommended
	include /home/ubuntu18/coreruleset/crs-setup.conf.example
        include /home/ubuntu18/coreruleset/rules/*.conf
}
reverse_proxy 192.168.0.36:60000
}

*************************************************************************************
fetch rules  via   git clone https://github.com/coreruleset/coreruleset.git

After remove REQUEST-922-MULTIPART-ATTACK.conf, All is ok

**Comment by fuomag9** [comment]
Same issue here

```
Dec 09 16:31:05 nginx caddy[33478]: Error: loading initial config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'waf': provision http.handlers.waf: failed to compile rule (unknown variable): &MULTIPART_PART_HEADERS:_charset_ "!@eq 0" "id:922100,phase:2,block,t:none,msg:'Multipart content type global _charset_ definition is not allowed by policy',logdata:'Matched Data: %{ARGS._charset_}',tag:'application-multi',tag:'language-multi',tag:'platform-multi',tag:'attack-multipart-header',tag:'OWASP_CRS',tag:'capec/1000/255/153',tag:'paranoia-level/1',ver:'OWASP_CRS/4.0.0-rc1',severity:'CRITICAL',chain"
```

**Comment by fuomag9** [comment]
Btw this is due to a modsecurity update that was done to fix a bypass, but I don't know why the same issue happens on coraza as well https://github.com/coreruleset/coreruleset/issues/2795

**Comment by jptosso** [comment]
Fixed in https://github.com/corazawaf/coraza-caddy/releases/tag/v1.2.2 !! Thank you for your report
