### ISSUE TITLE
Data race warning detected upon starting Caddy

### ISSUE THREAD

**Issue by r3g-5z** [corazawaf/coraza-caddy#44]
Hi! Our servers build Caddy with [Go's data race detector](https://go.dev/doc/articles/race_detector) and I've observed the following data race detections upon each server restart when any request comes in: https://gist.github.com/r3g-5z/19a4710c2a061c3248d27de4dde5ddae (logs are too long)

At the moment I'm setting up Coraza so my CRS is all default except for allowlisting the protocols HTTP/3 and HTTP/3.0 (`setvar:'tx.allowed_http_versions=HTTP/1.0 HTTP/1.1 HTTP/2 HTTP/2.0 HTTP/3 HTTP/3.0'`).

This warning only occurs once each restart, but it is consistent.

We're building Caddy from the main branch instead of the latest tag, and running and building with Go 1.20 (`go version go1.20 linux/amd64`).

**Comment by jcchavezs** [comment]
Interesting. I think the main issue here is that the action is mutating the rule which sounds odd to me as rules are persistent across the lifecycle of the WAF and we are mutating rules that contain `nolog` on transaction basis. Let me try to remove that. cc @anuraaga (as https://github.com/corazawaf/coraza/commit/fce26f25ab3e1955de7b396d01d6b43dc8c33b7b#diff-37cfb60455a57c6ad1051cd26e79e27f4bf533bd2cf7d09bac700c0974a73cf2R23) and @jptosso

**Comment by jptosso** [comment]
Thank you for your report, fixed in #45 which implements @jcchavezs fix

**Comment by r3g-5z** [comment]
Thanks! Will build and try again later
