### ISSUE TITLE
Coraza not act with rule on allow or pass when using SecDefultAction deny (implicit deny)

### ISSUE THREAD

**Issue by carlos-herrer** [corazawaf/coraza-caddy#46]
Hello,

 I am using Coraza with caddy and loading de CRS rules on my CaddyFile and the crs-setup.conf is configure with "SecDefaultAction phase:1,log,auditlog,pass" in this case when I create my own rules on the directives in the caddyfile and try to block, this working fine.

But if I try to change the default action for Deny on the crs-setup.conf by "SecDefaultAction phase:1,log,auditlog,deby,status:403" then when I try to make my own rules for permit access this not work, always block website.

This case works for someone ? I try to block any request and permit only the specifit uri (with the OWASP proteccion at lease)

**Comment by fzipi** [comment]
Thanks @carlos-herrer for your report. Will be taking a look shortly!

**Comment by fzipi** [comment]
@carlos-herrer I'm trying to find a reasonable answer for your use case, but I do not understand it properly. Can you add a sample of your rules? Are your rules in the same phase as this default action?

**Comment by carlos-herrer** [comment]
Hello @fzipi 
  I attached my caddyfile and the files of custom rules.
  for last question, no, i don't used the same phase as this default action.

 The default action is on the CRS-SETUP.conf and my custom are in another file like "SecRule" I also try on section 'Directive' but the result is the same (always block)

Caddyfile 

[Caddyfile.txt](https://github.com/corazawaf/coraza-caddy/files/10834001/Caddyfile.txt)

MyFile with my custom rules.

[custom-rules-coraza.conf.txt](https://github.com/corazawaf/coraza-caddy/files/10834002/custom-rules-coraza.conf.txt)

**Comment by carlos-herrer** [comment]
This is the CRS-Setup.conf on coraza loaded from crs repository with the OWAS rules this is the only change I did.

![image](https://user-images.githubusercontent.com/18275616/221419888-3a04e973-4ec9-471f-b393-5b78d9317f37.png)

**Comment by fzipi** [comment]
@carlos-herrer After taking a look I don't think you want to do it this way.

1. Just leave the default actions at pass. The CRS is smart and will do things properly.
2. Create two rules:
* one for allowing your IPs to the specified URL (you might need to use a couple of chained rules to achieve this)
* one for denying everything else

IMHO, this is the best approach.

**Comment by fzipi** [comment]
Ok, first thing: the problem doesn't seem to be related to coraza.

This looks more like a basic rule problem. Can we switch this to a different place, like [stackoverflow](https://stackoverflow.com/questions/tagged/mod-security)? There will be more eyes watching.

**Comment by carlos-herrer** [comment]
Hi @fzipi,

 But is normal that match on both rule? it would not stopped when match on the rule ID 2 ?

**Comment by M4tteoP** [comment]
Hi @carlos-herrer,
I tried to reproduce it in Coraza (with the HTTP go example), but the allow action is working as expected: `allow` of rule `2` is executed, and the server response back with a `200`.
Rules:
```
SecRule REQUEST_URI "/*.php" "id:2, allow, log, logdata:'try access to phpinfo', auditlog, phase:1, status:200" ##permit access to all php file.
SecRule REQUEST_URI "/^" "id:3, allow, log, logdata:' permit index or root page ',phase:1,status:200" ##permit access to the root page or index
#default deny
SecRule REQUEST_URI "/" "id:1,deny, log, logdata:' block all ',phase:1,status:403" ## deny anything else.
```
Logs:
```
[DEBUG] New transaction created
[DEBUG] Evaluating phase tx_id="iqxRzEseonuTkhByHDd" phase=1
[DEBUG] Evaluating rule tx_id="iqxRzEseonuTkhByHDd" rule_id=2
[DEBUG] Expanding arguments for rule tx_id="iqxRzEseonuTkhByHDd" rule_id=2
[DEBUG] Transforming argument for rule tx_id="iqxRzEseonuTkhByHDd" rule_id=2
[DEBUG] Arguments transformed for rule tx_id="iqxRzEseonuTkhByHDd" rule_id=2
[DEBUG] Matching rule tx_id="iqxRzEseonuTkhByHDd" rule_id=2 variable_name="REQUEST_URI" key=""
[DEBUG] Evaluating action tx_id="iqxRzEseonuTkhByHDd" action="log"
[DEBUG] Evaluating action tx_id="iqxRzEseonuTkhByHDd" action="logdata"
[DEBUG] Evaluating action tx_id="iqxRzEseonuTkhByHDd" action="auditlog"
[DEBUG] Evaluating operator: MATCH tx_id="iqxRzEseonuTkhByHDd" rule_id=2 operator_function="@rx" operator_data="/*.php" arg="/phpinfo.php"
[DEBUG] Executing disruptive action for rule tx_id="iqxRzEseonuTkhByHDd" rule_id=2 action="allow"
[DEBUG] Rule matched tx_id="iqxRzEseonuTkhByHDd" rule_id=2
[logError][emergency] [client "127.0.0.1"] Coraza: Warning.  [file "default.conf"] [line "0"] [id "2"] [rev ""] [msg ""] [data "try access to phpinfo"] [severity "emergency"] [ver ""] [maturity "0"] [accuracy "0"] [hostname ""] [uri "/phpinfo.php"] [unique_id "iqxRzEseonuTkhByHDd"]
[DEBUG] Finish evaluating rule tx_id="iqxRzEseonuTkhByHDd" rule_id=2
[DEBUG] Finished phase tx_id="iqxRzEseonuTkhByHDd" phase=1
[DEBUG] Evaluating phase tx_id="iqxRzEseonuTkhByHDd" phase=2
[DEBUG] Finished phase tx_id="iqxRzEseonuTkhByHDd" phase=2
[DEBUG] Evaluating phase tx_id="iqxRzEseonuTkhByHDd" phase=3
[DEBUG] Finished phase tx_id="iqxRzEseonuTkhByHDd" phase=3
[DEBUG] Evaluating phase tx_id="iqxRzEseonuTkhByHDd" phase=5
[DEBUG] Finished phase tx_id="iqxRzEseonuTkhByHDd" phase=5
[DEBUG] Transaction marked for audit logging tx_id="iqxRzEseonuTkhByHDd"
[DEBUG] Transaction finished tx_id="iqxRzEseonuTkhByHDd" is_interrupted=false
```
Are you running latest coraza-caddy master? The implementation of the allow actions has been merged [quite recently](https://github.com/corazawaf/coraza/pull/527).

**Comment by jcchavezs** [comment]
There is a misalignment of coraza http package and caddy which we need to sync. I think this might be also an effect of that. I will see if I can port the changes today.

**Comment by carlos-herrer** [comment]
Hello @M4tteoP I used xcaddy recently (yesterday) so I beleve I'm using the last version of coraza and I using caddy version 2.6.4. too

**Comment by jcchavezs** [comment]
Coraza-caddy might or might not use the latest version of coraza but the
real issue is the Middleware itself. Let me see if I can tackle this today.
