### ISSUE TITLE
runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by kkroo** [corazawaf/coraza-caddy#48]
## Description

Describe the issue that you're seeing.
caddy server container crashed with panic. hope this might help someone. great project thank you

> 
> cdn-in-a-box-caddy-1  | panic: runtime error: slice bounds out of range [862:0]
> cdn-in-a-box-caddy-1  |
> cdn-in-a-box-caddy-1  | goroutine 21235869 [running]:
> cdn-in-a-box-caddy-1  | github.com/corazawaf/coraza/v3/internal/corazawaf.(*bodyBufferReader).Read(0xc047d6cd50, {0xc038774000?, 0x0?, 0x7fce60935688?})
> cdn-in-a-box-caddy-1  |         github.com/corazawaf/coraza/v3@v3.0.0-20230117071831-8b909c7fc345/internal/corazawaf/body_buffer.go:98 +0x139
> cdn-in-a-box-caddy-1  | io.discard.ReadFrom({}, {0x1f8f960, 0xc047d6cd50})
> cdn-in-a-box-caddy-1  |         io/io.go:611 +0x72
> cdn-in-a-box-caddy-1  | io.copyBuffer({0x1f97800, 0x2ca05e0}, {0x1f8f960, 0xc047d6cd50}, {0xc05461a000, 0x8000, 0x8000})
> cdn-in-a-box-caddy-1  |         io/io.go:413 +0x14b
> cdn-in-a-box-caddy-1  | io.(*multiReader).writeToWithBuffer(0xc051094c48, {0x1f97800, 0x2ca05e0}, {0xc05461a000, 0x8000, 0x8000})
> cdn-in-a-box-caddy-1  |         io/multi.go:54 +0x125
> cdn-in-a-box-caddy-1  | io.(*multiReader).WriteTo(0x19bcd00?, {0x1f97800, 0x2ca05e0})
> cdn-in-a-box-caddy-1  |         io/multi.go:45 +0x56
> cdn-in-a-box-caddy-1  | io.copyBuffer({0x1f97800, 0x2ca05e0}, {0x7fce601809b8, 0xc047d4bbf0}, {0x0, 0x0, 0x0})
> cdn-in-a-box-caddy-1  |         io/io.go:409 +0x16e
> cdn-in-a-box-caddy-1  | io.Copy(...)
> cdn-in-a-box-caddy-1  |         io/io.go:386
> cdn-in-a-box-caddy-1  | net/http.(*transferWriter).doBodyCopy(0xc02cddcdc0, {0x1f97800?, 0x2ca05e0?}, {0x7fce601809b8?, 0xc047d4bbf0?})
> cdn-in-a-box-caddy-1  |         net/http/transfer.go:412 +0x4d
> cdn-in-a-box-caddy-1  | net/http.(*transferWriter).writeBody(0xc02cddcdc0, {0x1f8e160, 0xc0293ac640})
> cdn-in-a-box-caddy-1  |         net/http/transfer.go:375 +0x418
> cdn-in-a-box-caddy-1  | net/http.(*Request).write(0xc069109700, {0x1f8e160, 0xc0293ac640}, 0x0, 0x0, 0x0)
> cdn-in-a-box-caddy-1  |         net/http/request.go:701 +0xb46
> cdn-in-a-box-caddy-1  | net/http.(*persistConn).writeLoop(0xc0595f9b00)
> cdn-in-a-box-caddy-1  |         net/http/transport.go:2395 +0x174
> cdn-in-a-box-caddy-1  | created by net/http.(*Transport).dialConn
> cdn-in-a-box-caddy-1  |         net/http/transport.go:1752 +0x1791

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).
reverse proxy server being hammered by bots

### Expected result

What should happen?

### Actual result

What happened.

**Comment by jcchavezs** [comment]
I will try to get this done this week. We need to port changes from coraza
itself. Before I was trying to reuse the same abstraction but ended up with
the conclusion that it wasn't worth. Better to have duplication over a bad
abstraction.

**Comment by jcchavezs** [comment]
@kkroo we completely rewrite the connector. Do you mind testing again with latest commit?

**Comment by jcchavezs** [comment]
Ping @kkroo

**Comment by fzipi** [comment]
@kkroo Can you please help us getting this solved?
