### ISSUE TITLE
Unsure if load_owasp_crs is required for using the OWASP core rule set

### ISSUE THREAD

**Issue by BurningDog** [corazawaf/coraza-caddy#63]
I'm trying to use Coraza and the OWASP ruleset with Caddy 2.6.4 (this version of Caddy as it's the latest stable, and I'm using [API Platform](https://api-platform.com/) and its [Caddyfile](https://github.com/api-platform/demo/blob/main/api/docker/caddy/Caddyfile)).

I need to use the following lines to build caddy:

```sh
RUN xcaddy build \
	--with github.com/corazawaf/coraza-caddy \
	--with github.com/corazawaf/coraza-coreruleset
```

...otherwise the `conf` files mentioned in the [README](https://github.com/corazawaf/coraza-caddy#using-owasp-core-ruleset) don't exist  anywhere: `@coraza.conf-recommended`, `@crs-setup.conf.example`, `@owasp_crs/*.conf`. I manually copy those files to the correct locations:

```sh
cp /go/pkg/mod/github.com/corazawaf/coraza-coreruleset*/rules/@coraza.conf-recommended /etc/caddy/@coraza.conf-recommended
cp /go/pkg/mod/github.com/corazawaf/coraza-coreruleset*/rules/@crs-setup.conf.example /etc/caddy/@crs-setup.conf.example
cp /go/pkg/mod/github.com/corazawaf/coraza-coreruleset*/rules/@owasp_crs/* /etc/caddy/@owasp_crs/
```

My `Caddyfile` is as follows:

```
{
        # Debug
        {$CADDY_DEBUG}

        # must be always included in your Caddyfile for Coraza module to work
        # see https://github.com/corazawaf/coraza-caddy
        order coraza_waf first
}

{$SERVER_NAME}

route {
        coraza_waf {
                load_owasp_crs
                directives `
                Include @coraza.conf-recommended
                Include @crs-setup.conf.example
                Include @owasp_crs/*.conf
                SecRuleEngine On
                `
        }

        root * /srv/app/public

        php_fastcgi unix//var/run/php/php-fpm.sock
        encode zstd gzip
        file_server
}
```

I've used `caddy fmt --overwrite` to correctly format the `Caddyfile`.

However, when I run `caddy` I get this error:

> Error: adapting config using caddyfile: parsing caddyfile tokens for 'coraza_waf': Caddyfile:14 - Error during parsing: invalid key for filter directive: load_owasp_crs

However, if I comment out the `load_owasp_crs` directive, then caddy runs. Is this expected?

[Edit: after testing, the WAF is running, but I'm not sure how to check that the OWASP core rule set is running too?]

**Comment by ameyer8** [comment]
@BurningDog I had this issue too. It looks like `xcaddy` is pulling in the latest released version of coraza-caddy and that version doesn't have support for the built in rule set. You can force `xcaddy` to pull from master with this command:

`xcaddy build --with github.com/corazawaf/coraza-caddy@master`

I did not have to specify the `--with github.com/corazawaf/coraza-coreruleset`

**Comment by jcchavezs** [comment]
@BurningDog could you try what @ameyer8 suggests?

**Comment by jcchavezs** [comment]
Ping @BurningDog

**Comment by jcchavezs** [comment]
any movement on this?

**Comment by BurningDog** [comment]
Apologies for the long delay in my response - yes, the suggestion at https://github.com/corazawaf/coraza-caddy/issues/63#issuecomment-1560106130 worked. Thanks @ameyer8!
