### ISSUE TITLE
Caddy handle_errors not working with v2

### ISSUE THREAD

**Issue by skixmix** [corazawaf/coraza-caddy#88]
Hello,

Whilst working with the most recent version (v2) of this module, I observed that the handle_errors directive is no longer functional with the 403 code initiated by the WAF. However, in the v1.2.2 version of the module, this feature operates correctly.

My configuration (the commented parts are used in v2):
```
	# Error handling
	handle_errors {
		reverse_proxy http://localhost:5001 {
			respond "Hello"
		}
	}


        coraza_waf {
			# load_owasp_crs
			# directives `
			include /waf/coraza/coraza.conf-recommended
			include /waf/coreruleset/crs-setup.conf.example
			include /waf/coreruleset/rules/*.conf
			# `
        }
``` 

In version 1.2.2, the activation of a rule prompts the display of the "Hello" message. However, in version 2, the standard browser's 403 page is presented instead.

Thank you,
Simone

**Comment by jptosso** [comment]
@jcchavezs I can confirm it used to work, but something changed in how we handle errors. @jcchavezs  @M4tteoP

**Comment by M4tteoP** [comment]
Am I wrong to say that this issue can be closed? https://github.com/corazawaf/coraza-caddy/pull/164 added `handle_errors` to the example and to the readme 🤔

**Comment by BurningDog** [comment]
I wasn't able to get `handle_errors` working following the example (tried both options). Caddy v2.8.4 and Coraza `github.com/corazawaf/coraza-caddy@master`
