### ISSUE TITLE
New configuration not loaded on Caddy reload

### ISSUE THREAD

**Issue by skixmix** [corazawaf/coraza-caddy#89]
Hi,

You may have noticed that I am actively testing the module before utilizing it in production (kudos for the excellent work, by the way 😄 ). During my recent tests, I observed that in both versions 1.x and 2.x, the WAF configurations are not refreshed when I make changes to the .conf file and **reload** Caddy. However, if I **restart** the Caddy service, it functions properly (of course...).

This is associated with #11, which is closed, but reloading Caddy after modifying my configuration file, as mentioned, doesn't work.

Currently, the only method I have found is to modify the file name with an added random number, but this approach is not really "clean". Do you know if there is an alternative way to completely reload the WAF configuration for a specific site without restarting Caddy?

Thank you,
Simone

**Comment by skixmix** [comment]
Ok sorry I think I found the issue.

Essentially, Caddy operates in a manner where if it does not detect **any** alterations in the configuration (even if we modify sections), it does not execute an actual reload and instead displays a message similar to:

```
{"level":"info","ts":1689607946.3474102,"msg":"config is unchanged"}
{"level":"info","ts":1689607946.3475072,"logger":"admin.api","msg":"load complete"}
``` 

This happens if for example we have a configuration like:
```
(1_waf) {
        coraza_waf {
			include /myconfig.conf
        }
}
``` 
and somewhere in the config we import it:
```
import 1_waf
``` 

By modifying it to `(2_waf)` and importing it with `(2_waf)`, Caddy omits the block name and acknowledges that no modifications were made. The only option is to make an actual alteration in the current configuration, such as changing `/myconfig.conf` to `/myconfig1.conf`. Currently, instead of altering the file name, I am appending a custom header with a random value, which is a more cost-effective alternative compared to changing the file name.

Do you have other ideas?

Thank you,
Simone

**Comment by jcchavezs** [comment]
Thanks a lot! ping @mholt for advice.

also this should be documented, are you up to open a PR?

**Comment by jcchavezs** [comment]
wondering ir adding a timestamp inside a commented line before the import
would work?

**Comment by skixmix** [comment]
Hi,

Sure, I checked out [this section](https://caddyserver.com/docs/api#post-load) in the Caddy documentation yesterday. I gave it a try, and it's working smoothly now, without requiring any extra steps.

Thanks! 😃

**Comment by jcchavezs** [comment]
I think this problem isn't explicit enough. Are you up to add a
TROUBLESHOOTING.MD with such problem?

**Comment by skixmix** [comment]
Hello,

Certainly, I submitted the PR 😄
