### ISSUE TITLE
can't be built on Go 1.20

### ISSUE THREAD

**Issue by m-si** [corazawaf/coraza-caddy#90]
### Describe the bug
a build of corazawaf/coraza-caddy fails due to old requirement in go.mod line 69 with error:
```shell
/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.29.2/internal/qtls/go120.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration
```

### To Reproduce
Clone https://github.com/corazawaf/coraza-caddy and build:
```shell
git clone --depth 1 https://github.com/corazawaf/coraza-caddy
...
go build caddy/main.go
```

### ideas
Two ideas to solve the issue
- Either update quic-go (latest [release]( https://github.com/quic-go/quic-go/releases) seems to be far ahead.
- Alternativly switch to quic-go/quic-go like they did at [syncthing project](https://github.com/syncthing/syncthing/issues/8768)

**Comment by jcchavezs** [comment]
is this a caddy dependency or a coraza dependency?

**Comment by m-si** [comment]
First of all , thank you for your fast response. As I am new to this, it's a bit difficult to find out for me. I can't find it in their go.mod of v2.6.4 and v2.7 so I guess it seems to be a corazza requierment, isn't it?

**Comment by jcchavezs** [comment]
It is a Caddy dependency https://github.com/caddyserver/caddy/blob/master/go.mod#L20, we might need to upgrade this repo to latest caddy and go 1.19 once a new release. Any idea on when go 1.20 is going to be supported @mholt?

**Comment by jptosso** [comment]
I have tested caddy main and it works fine with go 1.20

**Comment by jcchavezs** [comment]
@jptosso could you add 1.19 and 1.20 to the CI and drop 1.18?

**Comment by jcchavezs** [comment]
Uhmm https://github.com/corazawaf/coraza-caddy/pull/91

**Comment by m-si** [comment]
@jcchavezs today I have no time, but I can try later this week. But to me, it looks even more promising to go with 1.19 or 1.20 as we need to do that anyway to keep up.

**Comment by mholt** [comment]
@jcchavezs To clarify, the latest Go is (almost?) always supported. We just have to support one prior Go release to please the Debian packaging gods. :man_shrugging:

**Comment by M4tteoP** [comment]
Since https://github.com/corazawaf/coraza-caddy/pull/96, we are building coraza-caddy in the CI with Go 1.20 and caddy is updated to v2.7.3, I think we can close this one
